export const mockFeedData = [
  {
    id: "post1",
    user: {
      username: "nigerian_red_cross",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
    },
    caption:
      "Urgent: Flooding in Lagos has displaced over 10,000 people. Our volunteers are on the ground providing emergency relief. Swipe to see how you can help. #LagosFlood #DisasterRelief",
    mediaUrl: "/placeholder.svg?height=800&width=450",
    mediaType: "image",
    timestamp: "2023-08-15T14:30:00Z",
    likes: 3245,
    isLiked: false,
    isSaved: false,
    location: "Lagos, Nigeria",
    tags: ["LagosFlood", "DisasterRelief", "Donations"],
    disasterInfo: {
      type: "Severe Flooding",
      donationEnabled: true,
    },
    comments: [
      {
        id: "comment1",
        username: "concerned_citizen",
        avatar: "/placeholder.svg?height=40&width=40",
        text: "This is heartbreaking. Just donated to support the relief efforts. Stay strong Lagos! 🙏",
        timestamp: "2023-08-15T15:20:00Z",
        likes: 42,
      },
      {
        id: "comment2",
        username: "lagos_community",
        avatar: "/placeholder.svg?height=40&width=40",
        text: "We're organizing local volunteers. DM us if you want to join the effort.",
        timestamp: "2023-08-15T16:05:00Z",
        likes: 28,
      },
      {
        id: "comment3",
        username: "relief_worker",
        avatar: "/placeholder.svg?height=40&width=40",
        text: "Currently at the Lekki relief center. We need more clean water and medical supplies urgently.",
        timestamp: "2023-08-15T17:30:00Z",
        likes: 56,
      },
    ],
    isFollowing: true,
  },
  {
    id: "post2",
    user: {
      username: "disaster_alert",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: true,
    },
    caption:
      "BREAKING: Flood waters rising in Abuja suburbs. Authorities urging immediate evacuation of low-lying areas. Share this information with anyone in the affected regions. #AbujaFlood #SafetyFirst",
    mediaUrl: "/placeholder.svg?height=800&width=450",
    mediaType: "video",
    timestamp: "2023-08-14T09:15:00Z",
    likes: 5621,
    isLiked: true,
    isSaved: true,
    location: "Abuja, Nigeria",
    tags: ["AbujaFlood", "Evacuation", "EmergencyAlert"],
    disasterInfo: {
      type: "Flash Flood Warning",
      donationEnabled: false,
    },
    comments: [
      {
        id: "comment4",
        username: "abuja_resident",
        avatar: "/placeholder.svg?height=40&width=40",
        text: "The Gwagwalada area is completely flooded. Roads are impassable. Please avoid!",
        timestamp: "2023-08-14T10:20:00Z",
        likes: 89,
      },
      {
        id: "comment5",
        username: "emergency_services",
        avatar: "/placeholder.svg?height=40&width=40",
        text: "Emergency services are stretched thin. If you're in a safe area, please stay where you are.",
        timestamp: "2023-08-14T11:05:00Z",
        likes: 124,
      },
    ],
    isFollowing: false,
  },
  {
    id: "post3",
    user: {
      username: "climate_action_ng",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: false,
    },
    caption:
      "The increasing frequency of floods in Nigeria is directly linked to climate change. We need both immediate relief AND long-term solutions. Join our advocacy campaign. #ClimateAction #FloodPrevention",
    mediaUrl: "/placeholder.svg?height=800&width=450",
    mediaType: "image",
    timestamp: "2023-08-13T16:45:00Z",
    likes: 1872,
    isLiked: false,
    isSaved: false,
    location: null,
    tags: ["ClimateAction", "FloodPrevention", "Advocacy"],
    disasterInfo: null,
    comments: [
      {
        id: "comment6",
        username: "environmental_scientist",
        avatar: "/placeholder.svg?height=40&width=40",
        text: "This is correct. Our research shows a 40% increase in extreme precipitation events in the last decade.",
        timestamp: "2023-08-13T17:30:00Z",
        likes: 67,
      },
      {
        id: "comment7",
        username: "policy_advocate",
        avatar: "/placeholder.svg?height=40&width=40",
        text: "We need better urban planning and drainage systems. The government must invest in infrastructure.",
        timestamp: "2023-08-13T18:15:00Z",
        likes: 53,
      },
    ],
    isFollowing: true,
  },
  {
    id: "post4",
    user: {
      username: "flood_survivor",
      avatar: "/placeholder.svg?height=40&width=40",
      verified: false,
    },
    caption:
      "Lost everything in the flood last night. My family is safe but we're currently in a shelter. Sharing my story to raise awareness about how quickly these disasters can happen. #PersonalStory #FloodSurvivor",
    mediaUrl: "/placeholder.svg?height=800&width=450",
    mediaType: "video",
    timestamp: "2023-08-12T20:10:00Z",
    likes: 9437,
    isLiked: false,
    isSaved: true,
    location: "Port Harcourt, Nigeria",
    tags: ["PersonalStory", "FloodSurvivor", "DisasterAwareness"],
    disasterInfo: {
      type: "Personal Flood Experience",
      donationEnabled: true,
    },
    comments: [
      {
        id: "comment8",
        username: "community_helper",
        avatar: "/placeholder.svg?height=40&width=40",
        text: "I'm in Port Harcourt and can bring some supplies. DMing you now.",
        timestamp: "2023-08-12T20:40:00Z",
        likes: 215,
      },
      {
        id: "comment9",
        username: "support_network",
        avatar: "/placeholder.svg?height=40&width=40",
        text: "We've set up a fundraiser for flood victims. Link in our bio. Stay strong! ❤️",
        timestamp: "2023-08-12T21:05:00Z",
        likes: 178,
      },
      {
        id: "comment10",
        username: "local_journalist",
        avatar: "/placeholder.svg?height=40&width=40",
        text: "Would you be willing to share your story for a news report? It could help raise more awareness.",
        timestamp: "2023-08-12T22:30:00Z",
        likes: 92,
      },
    ],
    isFollowing: false,
  },
]

export const mockCreators = [
  {
    id: "creator1",
    name: "Adebayo Johnson",
    username: "adebayo_speaks",
    avatar: "/placeholder.svg?height=80&width=80",
    followers: 245000,
    engagementRate: 4.8,
    completedProjects: 12,
    audience: "Young adults, Environmental activists",
    reliefExperience: true,
  },
  {
    id: "creator2",
    name: "Chioma Okafor",
    username: "chioma_reports",
    avatar: "/placeholder.svg?height=80&width=80",
    followers: 189000,
    engagementRate: 5.2,
    completedProjects: 8,
    audience: "News followers, Community leaders",
    reliefExperience: true,
  },
  {
    id: "creator3",
    name: "Emmanuel Nwachukwu",
    username: "emma_tech",
    avatar: "/placeholder.svg?height=80&width=80",
    followers: 320000,
    engagementRate: 3.7,
    completedProjects: 5,
    audience: "Tech enthusiasts, Young professionals",
    reliefExperience: false,
  },
  {
    id: "creator4",
    name: "Fatima Bello",
    username: "fatima_cares",
    avatar: "/placeholder.svg?height=80&width=80",
    followers: 178000,
    engagementRate: 6.1,
    completedProjects: 15,
    audience: "Charity supporters, Women's groups",
    reliefExperience: true,
  },
]

